### ISSUE TITLE
readme is no longer up to date with nyxt master

### ISSUE THREAD

**Issue by CorruptedVor** [efimerspan/nx-tailor#1]
following this commit https://github.com/atlas-engineer/nyxt/commit/0cb2c931a238735100e866a9d6d4920fbce6f911 you essentially need to rename a couple variables - i.e. text to on-background

**Comment by efimerspan** [comment]
Thanks for the heads up! Though I believe this shouldn't affect its functionality, since the `themes` slot of `tailor-mode` (where you specify the themes) basically inherits all slots from Nyxt's `theme` library bar the `cut` slot I added. However, I will update the example in the docs to reflect Nyxt's changes.

**Comment by CorruptedVor** [comment]
yep it's just a matter of configuring it a little different

**Comment by efimerspan** [comment]
Addressed with 1d191c3
